config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  
  root 'home#index'
  scope '/dashboard' do
    get '/', to: 'dashboard#index', :as => :dashboard
  end

  resources :dreams do
    resources :sequences
  end
  resources :characters
  resources :places

end

app/models/dream.rb
class DateValidator < ActiveModel::Validator
  def validate(dream)
    if Dream.where(date: dream.date).where(user_id: dream.user).count > 0
      dream.errors[:date] << I18n.t("dream.errors.date_already_taken")
    end
  end
end

class Dream < ApplicationRecord
  has_many :sequences, dependent: :destroy
  has_many :characters, through: :sequences
  has_many :places, through: :sequences
  belongs_to :user, required: true

  validates :feeling, inclusion: { in: %w(happy meh frown) }
  validates_with DateValidator
  scope :owned_by, ->(user) { where("user_id = ?", user.id) }

  def characters_count
    self.characters.length
  end

  def sequences_count
    self.sequences.length
  end

  def places_count
    self.places.length
  end

  def short_description
    {
      id: self.id,
      date: self.date,
      sequences_count: self.sequences_count,
      places_count: self.places_count,
      characters_count: self.characters_count,
      feeling: self.feeling
    }
  end
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  before_action :authenticate_user!
  layout 'board' 

  def index
    @dreams = Dream.owned_by current_user
  end

  def new
    @dream = Dream.new
  end

  def show
    @dream = Dream.find(params[:id])
    @moon = Lunartic.on_date((@dream.date+1.days).to_date)
  end

  def create
    @dream = Dream.new(dream_params)
    @dream.user = current_user
    if @dream.save
      if @dream.remembered?
        redirect_to :controller => 'sequences', :action => 'new', :dream_id => @dream.id
      else
        redirect_to :dashboard
      end
    else
      render "new"
    end
  end

  def update
    @dream = Dream.find(params[:id])
    if @dream.update_attributes(dream_params)
      redirect_to :dashboard
    else
      render 'edit'
    end
  end

  def edit
    @dream = Dream.find(params[:id])
  end


  def destroy
    Dream.find(params[:id]).destroy
    redirect_to dreams_url
  end

  def dream_params
    params.require(:dream).permit(:date, :feeling, :remembered)
  end
end

app/helpers/dream_helper.rb
module DreamHelper
end

app/views/dreams/_form.html.erb
<%= simple_form_for @dream, html: { novalidate: false } do |f| %>
  <%= f.input :date, label: I18n.t("dream.new.date"), :as => :date_picker, required: true %>

  <%= f.input :feeling, 
    :required => true,
    :label => I18n.t("dream.new.feeling"),
    :collection => [['happy', '<i class="fas fa-smile fa-2x"></i>'.html_safe], 
                    ['meh', ' <i class="fas fa-meh fa-2x"></i>'.html_safe],
                    ['frown', '<i class="fas fa-frown fa-2x"></i>'.html_safe]], 
    :label_method => :last, 
    :value_method => :first,
    :as => :radio_buttons, 
    :item_wrapper_class => 'inline'
    %>

  <%= f.input :remembered , 
              :required => true, 
              :as => :radio_buttons, 
              :collection => [['Oui', true], ['Non', false]], label:I18n.t("dream.new.remembered"),
              :item_wrapper_class => 'inline' %>

  <div class="submit-button">
    <%= f.button :submit, class:"btn btn-success", value: I18n.t("dream.new.next") %>
  </div>
  <div class="progress">
    <div class="progress-bar progress-bar-success" style="width: 50%">
      <span class="sr-only">50% Complete (success)</span>
    </div>
  </div>
<% end %>
<script type="text/javascript">
    $('.datetimepicker').datetimepicker();
</script>

app/views/dreams/edit.html.erb
<div class="form-dream">
  <div class="well">
     <div class="panel panel-default form-content">
        <div class="panel-heading"><i class="fa fa-chart-pie"></i><%= I18n.t("dream.new.title") %></div>
        <div class="panel-body ">
          <div class="dreams-explanations alert alert-info">
            <p><%= I18n.t("dream.new.explanation_1") %></p>
          </div>
          <%= render 'form' %>
        </div>
    </div>
  </div>
</div>

app/views/dreams/index.html.erb
<div class="dreams-table">
  <div class="panel panel-default">
    <div class="panel-heading"><%= I18n.t("dream.list") %></div>
    <div class="panel-body">
      <%= link_to I18n.t("dream.new.title"), new_dream_path, class:"btn btn-primary add-dream-btn" %>
      <!-- Table -->
      <table class="table table-striped table-bordered table-list">
        <thead>
          <tr>
            <th>Date</th>
            <th><%= I18n.t("dream.feeling") %></th>
            <th><%= I18n.t("dream.nb_sequences") %></th>
            <th><%= I18n.t("dream.nb_characters") %></th>
            <th><%= I18n.t("dream.nb_places") %></th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @dreams.each  do |dream| %>
            <tr>
              <td><%= I18n.localize dream.date %></td>
              <% if dream.feeling == "happy" %>
                <td><i class="fas fa-smile fa-stack-2x fa-flip-horizontal"></i></td>
              <% else %>
                <td><i class="fas fa-<%= dream.feeling %> fa-stack-2x fa-flip-horizontal"></i></td>
              <% end %>
              <td><%= dream.sequences.count %></td>
              <td><%= dream.characters.count %></td>
              <td><%= dream.places.count %></td>
              <td><%= link_to '<i class="fa fa-eye"></i>'.html_safe, dream %>
                  <%= link_to '<i class="fa fa-edit"></i>'.html_safe, [:edit, dream] %>
                  <%= link_to '<i class="fa fa-times"></i>'.html_safe, dream, method: :delete %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<script>
  $(document).ready(function() {
    var dataTable = $('.table').DataTable();

    document.addEventListener("turbolinks:before-cache", function() {
      if (dataTable !== null) {
        dataTable.destroy();
        dataTable = null;
      }
    });
  });
</script>

app/views/dreams/new.html.erb
<div class="form-dream">
  <div class="well">
     <div class="panel panel-default form-content">
        <div class="panel-heading"><i class="fa fa-chart-pie"></i><%= I18n.t("dream.new.title") %></div>
        <div class="panel-body ">
          <div class="dreams-explanations alert alert-info">
            <p><%= I18n.t("dream.new.explanation_1") %></p>
          </div>
          <%= render 'form' %>
        </div>
    </div>
  </div>
</div>

app/views/dreams/show.html.erb
<div class="show-dream">
  <div id="main-infos">
    <h3><%= I18n.t("dream.show.title", {date: I18n.localize(@dream.date)}) %></h3>
    <span>Lune : <%= (@moon.percent_full*100).round(1) %>% visible</span>
    <span> - </span>
    <span><%= @moon.phase %></span>
  </div>
  <div id="dream-content">
    <% @dream.sequences.each do |sequence| %>
      <%= render partial: "sequences/display", locals: {sequence: sequence} %>
    <% end %>
  </div>
</div>