config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  
  root 'home#index'
  scope '/dashboard' do
    get '/', to: 'dashboard#index', :as => :dashboard
  end

  resources :dreams do
    resources :sequences
  end
  resources :characters
  resources :places

end

app/models/sequence.rb
class Sequence < ApplicationRecord
  belongs_to :dream
  has_many :place_sequences
  has_many :places, through: :place_sequences
  has_many :character_sequences
  has_many :characters, through: :character_sequences

  scope :owned_by, ->(user) { joins(:dream).where("user_id = ?", user.id) }
end

app/controllers/sequences_controller.rb
class SequencesController < ApplicationController
  before_action :authenticate_user!
 layout 'board' 
  def new
    @dream =  Dream.find(params[:dream_id])
    @sequence = Sequence.new
  end

  def edit
    @dream =  Dream.find(params[:dream_id])
    @sequence = Sequence.find(params[:id])
  end

  def update
    @sequence = Sequence.find(params[:id])
    if @sequence.update_attributes(sequence_params)
      redirect_to :dashboard
    else
      render 'edit'
    end
  end

  def destroy
    Sequence.find(params[:id]).destroy
  end

  def create
    @sequence = Sequence.new(sequence_params)
    @sequence.dream_id = params[:dream_id]
    
    if @sequence.save
      if params.has_key?(:submit_and_new)
        redirect_to :controller => 'sequences', :action => 'new', :dream_id => @sequence.dream_id
      else
        redirect_to :dashboard
      end
    end
  end

  def sequence_params
    params.require(:sequence).permit(:name, :description, :character_ids=>[], :place_ids=>[])
  end
end

app/helpers/sequences_helper.rb
module SequencesHelper
end

app/views/sequences/_display.html.erb
<div class="well well-lg show-sequence">
  <div class="action-button">
  
    <%= link_to '<button class="btn btn-default btn-md"><i class="fa fa-edit"></i> Editer</button>'.html_safe, [:edit, sequence.dream, sequence]  %>
    <%= link_to '<button class="btn btn-default btn-md"><i class="fa fa-times"></i> Supprimer</button>'.html_safe, [sequence.dream, sequence], method: :delete %>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-primary">
        <div class="list-characters-heading panel-heading">
          <i class="fa fa-list"></i> Liste des personnes
        </div>
        <div class="panel-body">
          <ul class="list-group">
            <% sequence.characters.each do |character| %>
              <li>
                <%= character.complete_name %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-primary">
        <div class="panel-heading list-places-heading">
          <i class="fa fa-list"></i> Liste des lieux
        </div>
        <div class="panel-body">
          <ul class="list-group">
            <% sequence.places.each do |place| %>
              <li>
                <%= place.name %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="description">
      <%= sequence.description %>
    </div>
  </div>
</div>

app/views/sequences/_form.html.erb
<%= simple_form_for([@dream, @sequence], html: { novalidate: false }) do |f| %>
  <div class="form-inputs">
    <%= f.association :places, label: I18n.t("sequence.new.places"), collection: Place.owned_by(current_user), :label_method => lambda { |place| "#{place.name}" }, input_html: { class: 'multiselectplace'}, required: true %>
    <%= link_to I18n.t("place.new.title"), new_place_path, 
        data: { modal: true }, class:"btn btn-primary add-place-btn" %>
    <%= f.association :characters, label: I18n.t("sequence.new.characters"), collection: Character.owned_by(current_user), :label_method => lambda { |character| "#{character.first_name} #{character.last_name}" }, input_html: { class: 'multiselectcharacter'} %>
    <%= link_to I18n.t("character.new.title"), new_character_path, 
        data: { modal: true }, class:"btn btn-primary add-character-btn" %>
    <%= f.input :name, label: I18n.t("sequence.new.name"), required: true %>
    <%= f.input :description, label: I18n.t("sequence.new.description"), as: :text %>
  </div>
  <div class="submit-button">
    <%= f.button :submit, class:"btn btn-success", value: I18n.t("sequence.new.submit") %>
    <%= f.button :submit, class:"btn btn-success", name: "submit_and_new", value: I18n.t("sequence.new.submit_and_new") %>
  </div>
<% end %>

<script>


$(document).ready(function() {
    var multiSelect = $(".multiselectcharacter, .multiselectplace").multiselect({
        enableFiltering: true,
        filterBehavior: 'text',
        enableCaseInsensitiveFiltering: true,
    });

    document.addEventListener("turbolinks:before-cache", function() {
      if (multiSelect !== null) {
        multiSelect.remove();
        multiSelect = null;
      }
    });
  });
</script>

app/views/sequences/edit.html.erb
<div class="form-dream form-sequences">
  <div class="well">
     <div class="panel panel-default form-content">
        <div class="panel-heading"><i class="fa fa-chart-pie"></i><%= I18n.t("dream.new.title") %></div>
        <div class="panel-body ">
          <div class="dreams-explanations alert alert-info">
            <p><%= I18n.t("sequence.new.explanation_1") %></p>
          </div>
          <%= render 'form' %>
        </div>
    </div>
  </div>
</div>

app/views/sequences/new.html.erb
<div class="form-dream form-sequences">
  <div class="well">
     <div class="panel panel-default form-content">
        <div class="panel-heading"><i class="fa fa-chart-pie"></i><%= I18n.t("dream.new.title") %></div>
        <div class="panel-body ">
          <div class="dreams-explanations alert alert-info">
            <p><%= I18n.t("sequence.new.explanation_1") %></p>
          </div>
          <%= render 'form' %>
        </div>
    </div>
  </div>
</div>